# Generated by Django 4.0.4 on 2022-07-13 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='author',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.PROTECT,  # noqa
                                    related_name='author',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,  # noqa
                                    related_name='executor',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='Executor'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(related_name='labels',
                                         to='labels.labels',
                                         verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,  # noqa
                                    to='statuses.status',
                                    verbose_name='Status'),
        ),
    ]
