# Generated by Django 4.0.4 on 2022-06-08 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0001_initial'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('task_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Исполнитель', to=settings.AUTH_USER_MODEL)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Автор', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.labels', verbose_name='Метка')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.statuses', verbose_name='Статусы')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
