# Generated by Django 4.0.4 on 2022-06-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_assigned_user_alter_tasks_created_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='created_user',
        ),
    ]
