# Generated by Django 4.0.4 on 2022-06-07 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_tasks_created_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_user',
            field=models.ManyToManyField(related_name='Автор', to=settings.AUTH_USER_MODEL),
        ),
    ]
