# Generated by Django 4.0.4 on 2022-06-07 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_tasks_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_user',
            field=models.ManyToManyField(related_name='created_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
