# Generated by Django 4.0.4 on 2022-06-07 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_alter_tasks_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
