# Generated by Django 4.0.4 on 2022-07-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='label_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='labels',
            old_name='label_name',
            new_name='name',
        ),
    ]
