name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install poetry
          python -m pip install --upgrade pip
          poetry update
          make install
          pip install -r requirements.txt
      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          ROLL_KEY: ${{ secrets.ROLL_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
        run: |
          make test
          - name:  Coverage report
            uses: paambaati/codeclimate-action@v2.7.5
            env:
              CC_TEST_REPORTER_ID: 126f6bf1854ca35575654c8b7462fedfc64185d9b81a479f7c2dfa50ad3590d6
            with:
              coverageCommand: make coverage